os:
  edit: fresh --cmd session open-file . {{filename}}
  editAtLine: fresh --cmd session open-file . {{filename}}:{{line}}
  editAtLineAndWait: fresh --cmd session open-file . {{filename}}:{{line}} --wait
  editInTerminal: true

theme:
  activeBorderColor:
    - '#b7bdf8'
    - bold
  inactiveBorderColor:
    - '#a5adcb'
  optionsTextColor:
    - '#8aadf4'
  selectedLineBgColor:
    - '#363a4f'
  cherryPickedCommitBgColor:
    - '#494d64'
  cherryPickedCommitFgColor:
    - '#b7bdf8'
  unstagedChangesColor:
    - '#ed8796'
  defaultFgColor:
    - '#cad3f5'
  searchingActiveBorderColor:
    - '#eed49f'

authorColors:
  '*': '#b7bdf8'
